# Handling Date and Time variables/ Columns

Date and time values usually hold a lot of hidden information which prove to be useful and important in different kinds of analysis.

Ex : if the date is 23 August, 2012. 

Then it holds information such as : 
- Date of the day
- Month
- Year (these are the obvious ones)
- Day of the week 
- Is it a weekend
- which quarter is it
- which semester is it
and many more data points according to the need of analysis

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Load the data sets
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

### Working with dates

In [4]:
date.sample(5)

           date  product_id  city_id  orders
141  2018-12-17        1640       26       1
854  2019-07-12        4030        0       2
6    2018-11-21        1282       26       1
579  2018-08-13        7059       14      31
564  2019-03-08        4195       26       8

In [5]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [6]:
# converting date col to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [14]:
# Now extracting various types of attributes from that data 
#Extracting year

date['year'] = date['date'].dt.year
print(date.head())

        date  product_id  city_id  orders  year     month  day
0 2019-12-10        5628       25       3  2019  December   10
1 2018-08-15        3646       14     157  2018    August   15
2 2018-10-23        1859       25       1  2018   October   23
3 2019-08-17        7292       25       1  2019    August   17
4 2019-01-06        4344       25       3  2019   January    6

In [10]:
# Exatracting month
date['month'] = date['date'].dt.month
print(date.head())

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [15]:
# extracting month  with name
date['month'] = date['date'].dt.month_name()
print(date.head())

        date  product_id  city_id  orders  year     month  day
0 2019-12-10        5628       25       3  2019  December   10
1 2018-08-15        3646       14     157  2018    August   15
2 2018-10-23        1859       25       1  2018   October   23
3 2019-08-17        7292       25       1  2019    August   17
4 2019-01-06        4344       25       3  2019   January    6

In [16]:
# extracting date
date['day'] = date['date'].dt.day
print(date.head())

        date  product_id  city_id  orders  year     month  day
0 2019-12-10        5628       25       3  2019  December   10
1 2018-08-15        3646       14     157  2018    August   15
2 2018-10-23        1859       25       1  2018   October   23
3 2019-08-17        7292       25       1  2019    August   17
4 2019-01-06        4344       25       3  2019   January    6

In [17]:
# Extracting the day of the week
date['day_of_week'] = date['date'].dt.day_of_week
print(date.head())

        date  product_id  city_id  orders  year     month  day  day_of_week
0 2019-12-10        5628       25       3  2019  December   10            1
1 2018-08-15        3646       14     157  2018    August   15            2
2 2018-10-23        1859       25       1  2018   October   23            1
3 2019-08-17        7292       25       1  2019    August   17            5
4 2019-01-06        4344       25       3  2019   January    6            6

In [ ]:
# name of the day of the week 
date['day_of_week'] = date['date'].dt.day_name() # 0 indexed the days 
print(date.head())

        date  product_id  city_id  orders  year     month  day day_of_week
0 2019-12-10        5628       25       3  2019  December   10     Tuesday
1 2018-08-15        3646       14     157  2018    August   15   Wednesday
2 2018-10-23        1859       25       1  2018   October   23     Tuesday
3 2019-08-17        7292       25       1  2019    August   17    Saturday
4 2019-01-06        4344       25       3  2019   January    6      Sunday

In [19]:
# Check if it's the weekend
date['Weekend'] = np.where(date['day_of_week'].isin(['Saturday', 'Sunday']), 1, 0)
date.head()

,date,product_id,city_id,orders,year,month,day,day_of_week,Weekend
0,2019-12-10,5628,25,3,2019,December,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,August,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,October,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,August,17,Saturday,1
4,2019-01-06,4344,25,3,2019,January,6,Sunday,1

In [ ]:
#extract time elapsed between two dates
import datetime 

today = datetime.datetime.today()

print((today - date['date']).head())
print("\n", (today - date['date']).dt.days.head()) # prints just the days

0   2290 days 17:10:10.410090
1   2772 days 17:10:10.410090
2   2703 days 17:10:10.410090
3   2405 days 17:10:10.410090
4   2628 days 17:10:10.410090
Name: date, dtype: timedelta64[us]

 0    2290
1    2772
2    2703
3    2405
4    2628
Name: date, dtype: int64

## Dealing with time

In [27]:
# Convert to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.sample(5)

                   date                                                msg
687 2012-01-25 16:44:00                   какие  имена  подходят  анатолий
491 2016-03-26 23:56:00  есть в чате волшебник с палочкой?прилети ко мн...
715 2014-05-26 01:04:00    Парень фитнес модель 25лет встречусь.0990991317
155 2013-11-08 00:23:00  хочу попробовать в машине. Карина  22 года  си...
228 2013-11-01 23:36:00  ПРИЕДУ В ГОСТИ К ЖЕНЩИНЕ СЕЙЧАС. Днепр. 063 41...

In [28]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [33]:
# extracting time attributes - hour, mins, secs
time['hour'] = time['date'].dt.hour
time['mins'] = time['date'].dt.minute
time['secs'] = time['date'].dt.second

time.head()

,date,msg,hour,mins,secs
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [35]:
#Extract time as a whole
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,mins,secs,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00